
	<footer>
		<div class="container">
			<div class="row">
				<ul class="mx-auto">
											<li><a href="https://pixeldusche.com/creme21/de/kontakt/" title="Kontakt">Kontakt</a></li>
						<li><a href="https://pixeldusche.com/creme21/de/faq/" title="FAQ">FAQ</a></li>
						<li><a href="https://pixeldusche.com/creme21/de/zahlungsmittel/" title="Zahlungsmittel">Zahlungsmittel</a></li>
						<li><a href="https://pixeldusche.com/creme21/de/versandkosten/" title="Versandkosten">Versandkosten</a></li>
						<li><a href="https://pixeldusche.com/creme21/de/agbs/" title="AGBs">AGBs</a></li>
						<li><a href="https://pixeldusche.com/creme21/de/widerruf/" title="Widerruf">Widerruf</a></li>
						<li><a href="https://pixeldusche.com/creme21/de/impressum/" title="Impressum">Impressum</a></li>
						<li><a href="https://pixeldusche.com/creme21/de/datenschutz/" title="Datenschutz">Datenschutz</a></li>

				</ul>
				<div class="col-12 text_footer">
					<img src="shop/images/Claim.svg" class="claim" alt="Creme21. Meine Lieblingspflege" width="600" />
				</div>
			</div>
		</div>
	</footer>

</div>
