DROP TABLE `morp_blog`;
CREATE TABLE `morp_blog` (  `fBlogID` int(11) NOT NULL AUTO_INCREMENT,  `fTitle` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',  `fSubtitle` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',  `fText` text CHARACTER SET utf8 NOT NULL,  `fAbstr` text CHARACTER SET utf8 NOT NULL,  `fVon` date NOT NULL DEFAULT '0000-00-00',  `fBis` date NOT NULL DEFAULT '0000-00-00',  `fDatum` date NOT NULL DEFAULT '0000-00-00',  `edit` int(1) NOT NULL DEFAULT '1',  `fAuthor` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',  `fLink` varchar(250) CHARACTER SET utf8 NOT NULL DEFAULT '',  `fBlogKatID` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '1',  `pid` int(11) NOT NULL DEFAULT '0',  `img1` varchar(150) CHARACTER SET utf8 NOT NULL DEFAULT '',  `img2` varchar(150) CHARACTER SET utf8 NOT NULL DEFAULT '',  `img3` varchar(150) CHARACTER SET utf8 NOT NULL DEFAULT '',  `img4` varchar(150) CHARACTER SET utf8 NOT NULL DEFAULT '',  `sichtbar` int(1) NOT NULL DEFAULT '1',  `multisel` varchar(255) COLLATE latin1_general_ci NOT NULL,  `fLanguage` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`fBlogID`)) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
DROP TABLE `morp_blog_kat`;
CREATE TABLE `morp_blog_kat` (  `fBlogKatID` int(11) NOT NULL AUTO_INCREMENT,  `fKat` varchar(255) NOT NULL,  `fLanguage` int(1) NOT NULL DEFAULT '1',  PRIMARY KEY (`fBlogKatID`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_angebote`;
CREATE TABLE `morp_cms_angebote` (  `aid` int(11) NOT NULL AUTO_INCREMENT,  `aTitle` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `aDesc` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `aPreis` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `img1` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `img2` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `img3` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `img4` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `sichtbar` int(11) NOT NULL,  `datumende` varchar(10) NOT NULL,  `mail` varchar(255) NOT NULL,  `fon` varchar(255) NOT NULL,  `mid` int(11) NOT NULL,  `isAngebot` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`aid`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_content`;
CREATE TABLE `morp_cms_content` (  `cid` int(11) NOT NULL AUTO_INCREMENT,  `navid` int(11) NOT NULL,  `vid` int(11) NOT NULL,  `vorlage` int(1) NOT NULL,  `vorl_name` varchar(30) COLLATE utf8_unicode_ci NOT NULL,  `content` text COLLATE utf8_unicode_ci,  `edit` int(1) NOT NULL DEFAULT '1',  `pos` int(11) NOT NULL DEFAULT '1',  `img0` int(11) DEFAULT NULL,  `img1` int(11) DEFAULT NULL,  `img2` int(11) DEFAULT NULL,  `img3` int(11) DEFAULT NULL,  `layout` int(1) NOT NULL DEFAULT '1',  `img4` int(11) NOT NULL DEFAULT '0',  `img5` int(11) NOT NULL DEFAULT '0',  `img6` int(11) NOT NULL DEFAULT '0',  `tid` int(11) NOT NULL,  `ton` int(1) NOT NULL DEFAULT '1',  `tpos` int(11) NOT NULL,  `tlink` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,  `tbackground` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,  `timage` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `theadl` varchar(80) COLLATE utf8_unicode_ci NOT NULL,  `theight` int(11) NOT NULL,  `twidth` int(11) NOT NULL,  `tcolor` varchar(6) COLLATE utf8_unicode_ci NOT NULL,  `tref` int(11) NOT NULL,  `tende` int(1) NOT NULL,  `tabstand` int(1) NOT NULL,  PRIMARY KEY (`cid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PACK_KEYS=0 ROW_FORMAT=DYNAMIC;
DROP TABLE `morp_cms_content_history`;
CREATE TABLE `morp_cms_content_history` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `datum` varchar(25) COLLATE utf8_unicode_ci NOT NULL,  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  `cid` int(11) NOT NULL,  `navid` int(11) NOT NULL,  `vid` int(11) NOT NULL,  `vorlage` int(1) NOT NULL,  `vorl_name` varchar(30) COLLATE utf8_unicode_ci NOT NULL,  `content` text COLLATE utf8_unicode_ci,  `edit` int(1) NOT NULL DEFAULT '1',  `pos` int(11) NOT NULL DEFAULT '1',  `img0` int(11) DEFAULT NULL,  `img1` int(11) DEFAULT NULL,  `img2` int(11) DEFAULT NULL,  `img3` int(11) DEFAULT NULL,  `layout` int(1) NOT NULL DEFAULT '1',  `img4` int(11) NOT NULL DEFAULT '0',  `img5` int(11) NOT NULL DEFAULT '0',  `img6` int(11) NOT NULL DEFAULT '0',  `tid` int(11) NOT NULL,  `ton` int(1) NOT NULL DEFAULT '1',  `tpos` int(11) NOT NULL,  `tlink` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,  `tbackground` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,  `timage` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `theadl` varchar(80) COLLATE utf8_unicode_ci NOT NULL,  `theight` int(11) NOT NULL,  `twidth` int(11) NOT NULL,  `tcolor` varchar(6) COLLATE utf8_unicode_ci NOT NULL,  `tref` int(11) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PACK_KEYS=0 ROW_FORMAT=DYNAMIC;
DROP TABLE `morp_cms_form`;
CREATE TABLE `morp_cms_form` (  `fid` int(11) NOT NULL AUTO_INCREMENT,  `fname` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `inpnm` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `edit` int(1) NOT NULL DEFAULT '1',  `fform` text COLLATE utf8_unicode_ci NOT NULL,  `fval` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `post` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `betreff` varchar(150) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `antwort` text COLLATE utf8_unicode_ci NOT NULL,  `extended` int(1) NOT NULL,  PRIMARY KEY (`fid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_form_auswertung`;
CREATE TABLE `morp_cms_form_auswertung` (  `aid` int(11) NOT NULL AUTO_INCREMENT,  `vorname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `wahrnehmung` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `arbeiter` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `beruf` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `alter` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `newsletter` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `wahrnehmungX` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `wohnort` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `newsletter_topic` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `malsehen` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `come` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `ggggg` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `morp_cms_news` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `nachricht` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `anrede` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `anruf` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `vname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `fon` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `organisation` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `anzahl_teilnehmer` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `bemerkung` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `geo3_4` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `prof_sql` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `mapping_01` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `spatial_sql` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `tile_services` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `geboren` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `medikamentenname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `ueberweisung` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `kommentar` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`aid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_form_field`;
CREATE TABLE `morp_cms_form_field` (  `ffid` int(11) NOT NULL AUTO_INCREMENT,  `fid` int(11) NOT NULL,  `art` varchar(20) COLLATE utf8_unicode_ci NOT NULL,  `feld` varchar(20) COLLATE utf8_unicode_ci NOT NULL,  `desc` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `hilfe` text COLLATE utf8_unicode_ci NOT NULL,  `spalte` varchar(20) COLLATE utf8_unicode_ci NOT NULL,  `reihenfolge` int(11) NOT NULL,  `pflicht` int(1) NOT NULL,  `email` int(1) NOT NULL,  `auswahl` text COLLATE utf8_unicode_ci NOT NULL,  `size` int(11) NOT NULL,  `parent` varchar(30) COLLATE utf8_unicode_ci NOT NULL,  `fehler` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `klasse` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `cont` varchar(20) COLLATE utf8_unicode_ci NOT NULL,  `fmin` int(11) NOT NULL,  `fmax` int(11) NOT NULL,  PRIMARY KEY (`ffid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_galerie`;
CREATE TABLE `morp_cms_galerie` (  `gid` int(11) NOT NULL AUTO_INCREMENT,  `gname` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,  `tn` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,  `gnid` int(11) NOT NULL DEFAULT '0',  `gtextde` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `gtexten` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `gpix` varchar(12) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `gsize` int(11) NOT NULL DEFAULT '0',  `sort` int(11) NOT NULL DEFAULT '1',  `gdatum` date NOT NULL,  `tags` text COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`gid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_galerie_comments`;
CREATE TABLE `morp_cms_galerie_comments` (  `commentsID` int(11) NOT NULL AUTO_INCREMENT,  `gid` int(11) NOT NULL,  `comment` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `mid` int(11) NOT NULL,  `dat` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  `parentID` int(11) NOT NULL,  PRIMARY KEY (`commentsID`),  UNIQUE KEY `commentsID` (`commentsID`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_galerie_group`;
CREATE TABLE `morp_cms_galerie_group` (  `ggid` int(11) NOT NULL AUTO_INCREMENT,  `ggname` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `sort` int(11) DEFAULT NULL,  `gglink` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `sichtbar` int(1) NOT NULL DEFAULT '1',  `date` varchar(12) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`ggid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_galerie_likes`;
CREATE TABLE `morp_cms_galerie_likes` (  `likesID` int(11) NOT NULL AUTO_INCREMENT,  `mid` int(11) NOT NULL,  `gid` int(11) NOT NULL,  PRIMARY KEY (`likesID`),  UNIQUE KEY `mid` (`mid`,`gid`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_galerie_name`;
CREATE TABLE `morp_cms_galerie_name` (  `gnid` int(11) NOT NULL AUTO_INCREMENT,  `gnname` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `ggid` int(11) NOT NULL DEFAULT '0',  `img` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `date` date NOT NULL,  `textde` text COLLATE utf8_unicode_ci NOT NULL,  `texten` text COLLATE utf8_unicode_ci NOT NULL,  `gntextde` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `gntexten` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `besucher` int(11) NOT NULL DEFAULT '0',  `sort` int(11) NOT NULL DEFAULT '0',  `sichtbar` int(1) NOT NULL DEFAULT '1',  `mid` int(11) NOT NULL,  `tags` text COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`gnid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_image`;
CREATE TABLE `morp_cms_image` (  `imgid` int(11) NOT NULL AUTO_INCREMENT,  `navid` int(11) NOT NULL DEFAULT '0',  `pos` int(11) NOT NULL DEFAULT '0',  `type` int(11) NOT NULL DEFAULT '0',  `size` int(11) NOT NULL DEFAULT '0',  `imgname` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `gid` int(11) NOT NULL DEFAULT '0',  `edit` int(1) NOT NULL DEFAULT '1',  `itext` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `longtext` text COLLATE utf8_unicode_ci NOT NULL,  `image` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`imgid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PACK_KEYS=0;
DROP TABLE `morp_cms_img_group`;
CREATE TABLE `morp_cms_img_group` (  `gid` int(11) NOT NULL AUTO_INCREMENT,  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `art` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`gid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PACK_KEYS=0;
DROP TABLE `morp_cms_meinungen`;
CREATE TABLE `morp_cms_meinungen` (  `tid` int(11) NOT NULL AUTO_INCREMENT,  `topicID` int(11) NOT NULL,  `tTitle` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `tText` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `img1` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `sichtbar` int(11) NOT NULL,  `datumende` varchar(10) NOT NULL,  `mail` varchar(255) NOT NULL,  `fon` varchar(255) NOT NULL,  `mid` int(11) NOT NULL,  `datum` varchar(10) NOT NULL,  PRIMARY KEY (`tid`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_meinungen_comments`;
CREATE TABLE `morp_cms_meinungen_comments` (  `commentsID` int(11) NOT NULL AUTO_INCREMENT,  `tid` int(11) NOT NULL,  `comment` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `mid` int(11) NOT NULL,  `dat` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  `parentID` int(11) NOT NULL,  PRIMARY KEY (`commentsID`),  UNIQUE KEY `commentsID` (`commentsID`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_meinungen_likes`;
CREATE TABLE `morp_cms_meinungen_likes` (  `likesID` int(11) NOT NULL AUTO_INCREMENT,  `mid` int(11) NOT NULL,  `tid` int(11) NOT NULL,  PRIMARY KEY (`likesID`),  UNIQUE KEY `mid` (`mid`,`tid`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_meinungen_topics`;
CREATE TABLE `morp_cms_meinungen_topics` (  `topicID` int(11) NOT NULL AUTO_INCREMENT,  `topicTitle` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `topicDesc` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `img1` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `sichtbar` int(11) NOT NULL,  PRIMARY KEY (`topicID`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_nav`;
CREATE TABLE `morp_cms_nav` (  `navid` int(11) NOT NULL AUTO_INCREMENT,  `ebene` int(11) NOT NULL DEFAULT '0',  `parent` int(11) NOT NULL DEFAULT '0',  `sort` int(11) NOT NULL DEFAULT '0',  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `fbimage` varchar(200) COLLATE utf8_unicode_ci NOT NULL,  `anker` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `oldlnk` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `setlink` varchar(150) COLLATE utf8_unicode_ci NOT NULL,  `shortlink` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `lnk` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `sichtbar` int(1) NOT NULL DEFAULT '1',  `edit` int(1) NOT NULL DEFAULT '1',  `keyw` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `desc` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `lang` int(1) NOT NULL DEFAULT '1',  `lock` int(1) NOT NULL DEFAULT '0',  `bereich` int(1) NOT NULL DEFAULT '1',  `button` varchar(20) COLLATE utf8_unicode_ci NOT NULL,  `bheight` int(1) NOT NULL,  `emotional` int(11) NOT NULL,  `design` int(11) NOT NULL,  `nocontent` int(1) NOT NULL,  `accesskey` varchar(2) COLLATE utf8_unicode_ci NOT NULL,  `langpar` int(11) NOT NULL,  `blog` int(1) NOT NULL,  `datum` varchar(10) COLLATE utf8_unicode_ci NOT NULL,  `author` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`navid`),  UNIQUE KEY `navid` (`ebene`,`navid`,`parent`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PACK_KEYS=0;
DROP TABLE `morp_cms_news`;
CREATE TABLE `morp_cms_news` (  `nid` int(11) NOT NULL AUTO_INCREMENT,  `ntitle` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',  `nmovie` varchar(255) CHARACTER SET utf8 NOT NULL,  `ntext` text CHARACTER SET utf8 NOT NULL,  `nvon` date NOT NULL DEFAULT '0000-00-00',  `nbis` date NOT NULL DEFAULT '0000-00-00',  `nerstellt` date NOT NULL DEFAULT '0000-00-00',  `nuhr` varchar(100) CHARACTER SET utf8 NOT NULL,  `ntag` varchar(50) CHARACTER SET utf8 NOT NULL,  `nort` varchar(255) CHARACTER SET utf8 NOT NULL,  `nlat` varchar(50) CHARACTER SET utf8 NOT NULL,  `edit` int(1) NOT NULL DEFAULT '1',  `aktuell` int(1) NOT NULL DEFAULT '1',  `nabstr` text CHARACTER SET utf8 NOT NULL,  `nautor` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',  `imgid` int(11) NOT NULL DEFAULT '0',  `nlink` varchar(250) CHARACTER SET utf8 NOT NULL DEFAULT '',  `ngid` int(11) NOT NULL DEFAULT '1',  `nsubtitle` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',  `pid` int(11) NOT NULL DEFAULT '0',  `style` int(1) NOT NULL DEFAULT '1',  `img1` varchar(150) CHARACTER SET utf8 NOT NULL DEFAULT '',  `img2` varchar(150) CHARACTER SET utf8 NOT NULL DEFAULT '',  `img3` varchar(150) CHARACTER SET utf8 NOT NULL DEFAULT '',  `img4` varchar(150) CHARACTER SET utf8 NOT NULL DEFAULT '',  `hid` int(11) NOT NULL,  `sichtbar` int(1) NOT NULL DEFAULT '1',  `icon` varchar(50) CHARACTER SET utf8 NOT NULL,  `nMetaTitle` varchar(100) CHARACTER SET utf8 NOT NULL,  `nMetaDesc` varchar(255) CHARACTER SET utf8 NOT NULL,  `tags` text COLLATE latin1_general_ci NOT NULL,  PRIMARY KEY (`nid`)) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
DROP TABLE `morp_cms_news_group`;
CREATE TABLE `morp_cms_news_group` (  `ngid` int(11) NOT NULL AUTO_INCREMENT,  `ngname` varchar(40) COLLATE utf8_unicode_ci NOT NULL,  `edit` int(1) NOT NULL DEFAULT '1',  `format` int(1) NOT NULL DEFAULT '1',  `nlang` int(1) NOT NULL DEFAULT '1',  `targetID` int(11) NOT NULL,  PRIMARY KEY (`ngid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_pdf`;
CREATE TABLE `morp_cms_pdf` (  `pid` int(11) NOT NULL AUTO_INCREMENT,  `pdesc` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `plong` text COLLATE utf8_unicode_ci NOT NULL,  `pname` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `psize` int(11) NOT NULL DEFAULT '0',  `pdate` date NOT NULL DEFAULT '0000-00-00',  `pgid` int(11) NOT NULL DEFAULT '1',  `edit` int(1) NOT NULL DEFAULT '0',  `pimage` varchar(150) COLLATE utf8_unicode_ci NOT NULL,  `pstart` date NOT NULL,  `pend` date NOT NULL,  `locked` int(11) NOT NULL,  `counter` int(11) NOT NULL,  PRIMARY KEY (`pid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_pdf_count`;
CREATE TABLE `morp_cms_pdf_count` (  `countID` int(11) NOT NULL AUTO_INCREMENT,  `pid` int(11) NOT NULL,  `mid` int(11) NOT NULL,  `datum` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  PRIMARY KEY (`countID`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_pdf_group`;
CREATE TABLE `morp_cms_pdf_group` (  `pgid` int(11) NOT NULL AUTO_INCREMENT,  `pgname` varchar(255) NOT NULL,  `parent` int(11) NOT NULL,  `pgart` int(1) NOT NULL,  `pghl` varchar(255) NOT NULL,  `img1` varchar(255) NOT NULL,  PRIMARY KEY (`pgid`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_pdf_group__`;
CREATE TABLE `morp_cms_pdf_group__` (  `pgid` int(11) NOT NULL,  `pgname` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `parent` int(11) NOT NULL,  `pgart` int(1) NOT NULL DEFAULT '1',  `pghl` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `img1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`pgid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_pfad`;
CREATE TABLE `morp_cms_pfad` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `url` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `navid` int(11) NOT NULL DEFAULT '0',  `parent` int(11) NOT NULL DEFAULT '0',  `page` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `wg` int(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_protokoll`;
CREATE TABLE `morp_cms_protokoll` (  `prid` int(11) NOT NULL AUTO_INCREMENT,  `id` int(11) NOT NULL DEFAULT '0',  `db` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `uid` int(11) NOT NULL DEFAULT '0',  `datum` date NOT NULL DEFAULT '0000-00-00',  `art` varchar(6) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  PRIMARY KEY (`prid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_cms_telegram`;
CREATE TABLE `morp_cms_telegram` (  `tid` int(11) NOT NULL AUTO_INCREMENT,  `tTitle` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `tText` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `img1` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `sichtbar` int(11) NOT NULL,  `datumende` varchar(10) NOT NULL,  `mail` varchar(255) NOT NULL,  `fon` varchar(255) NOT NULL,  `mid` int(11) NOT NULL,  `datum` varchar(10) NOT NULL,  PRIMARY KEY (`tid`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_telegram_comments`;
CREATE TABLE `morp_cms_telegram_comments` (  `commentsID` int(11) NOT NULL AUTO_INCREMENT,  `tid` int(11) NOT NULL,  `comment` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `mid` int(11) NOT NULL,  `dat` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  `parentID` int(11) NOT NULL,  PRIMARY KEY (`commentsID`),  UNIQUE KEY `commentsID` (`commentsID`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_cms_user`;
CREATE TABLE `morp_cms_user` (  `uid` int(11) NOT NULL AUTO_INCREMENT,  `uname` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `pw` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `berechtigung` int(11) DEFAULT NULL,  `admin` int(1) NOT NULL DEFAULT '0',  `email` varchar(150) COLLATE utf8_unicode_ci NOT NULL,  `title` varchar(10) COLLATE utf8_unicode_ci NOT NULL,  `lastname` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `firstname` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `auths` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`uid`)) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `morp_cms_user` VALUES('1', 'morpheus', 'db04cce4e9bafc1aaabbb7ceb7b5a2c5', '2', '1', 'post@pixel-dusche.de', 'Herr', 'Knetter', 'Björn', '20|30|40|50|60');
INSERT INTO `morp_cms_user` VALUES('2', 'admin', 'e10adc3949ba59abbe56e057f20f883e', '1', '1', '', '', '', '', '');
INSERT INTO `morp_cms_user` VALUES('3', 'Text', 'e10adc3949ba59abbe56e057f20f883e', '2', '0', '', '', '', '', '10');
INSERT INTO `morp_cms_user` VALUES('4', 'News', 'e10adc3949ba59abbe56e057f20f883e', '2', '0', '', '', '', '', '14');
INSERT INTO `morp_cms_user` VALUES('5', 'Doks', 'e10adc3949ba59abbe56e057f20f883e', '2', '0', '', '', '', '', '30');
INSERT INTO `morp_cms_user` VALUES('6', 'conny', 'ed063361b766f99800cb53ceab496497', '2', '1', '', '', '', '', '');
DROP TABLE `morp_color`;
CREATE TABLE `morp_color` (  `colid` int(11) NOT NULL AUTO_INCREMENT,  `color` varchar(7) NOT NULL,  `colname` varchar(20) NOT NULL,  PRIMARY KEY (`colid`)) ENGINE=MyISAM AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;
INSERT INTO `morp_color` VALUES('4', 'fff', 'bg-weiss');
INSERT INTO `morp_color` VALUES('5', 'ededed', 'hell-grau');
DROP TABLE `morp_download`;
CREATE TABLE `morp_download` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `benutzer` int(11) DEFAULT NULL,  `pid` int(11) NOT NULL,  `datei` char(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `onceagain` tinyint(4) NOT NULL DEFAULT '0',  `angelegt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  `aktiv` int(1) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PACK_KEYS=1;
DROP TABLE `morp_einladung_liste`;
CREATE TABLE `morp_einladung_liste` (  `eid` int(11) NOT NULL AUTO_INCREMENT,  `id` int(11) NOT NULL,  `mid` int(11) NOT NULL,  `confirmed` int(11) NOT NULL,  `anzahlPersonen` int(11) NOT NULL,  `kommentar` text NOT NULL,  PRIMARY KEY (`eid`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_event_kategorie`;
CREATE TABLE `morp_event_kategorie` (  `kid` int(11) NOT NULL AUTO_INCREMENT,  `bezeichnung` text NOT NULL,  `reihenfolge1` int(11) NOT NULL,  PRIMARY KEY (`kid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
DROP TABLE `morp_event_orte`;
CREATE TABLE `morp_event_orte` (  `oid` int(11) NOT NULL AUTO_INCREMENT,  `stadt` varchar(255) CHARACTER SET latin1 NOT NULL DEFAULT '',  `veranstOrt` varchar(255) CHARACTER SET latin1 NOT NULL DEFAULT '',  `www` varchar(255) CHARACTER SET latin1 NOT NULL DEFAULT '',  `text` text CHARACTER SET latin1,  `strasse` varchar(50) CHARACTER SET latin1 NOT NULL,  `plz` varchar(6) CHARACTER SET latin1 NOT NULL,  PRIMARY KEY (`oid`),  FULLTEXT KEY `veranstOrt` (`veranstOrt`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
DROP TABLE `morp_event_zusage`;
CREATE TABLE `morp_event_zusage` (  `zusageid` int(11) NOT NULL AUTO_INCREMENT,  `eventid` int(11) NOT NULL,  `mid` int(11) NOT NULL,  `datumZusage` varchar(10) NOT NULL,  `anzahlBegleitung` int(11) NOT NULL,  PRIMARY KEY (`zusageid`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_events`;
CREATE TABLE `morp_events` (  `eventid` int(11) NOT NULL AUTO_INCREMENT,  `eventName` varchar(255) NOT NULL,  `eventOrt` varchar(255) NOT NULL,  `oid` int(11) NOT NULL DEFAULT '1',  `mid` int(11) NOT NULL DEFAULT '1',  `kid` int(11) NOT NULL DEFAULT '8',  `eventDatum` varchar(10) NOT NULL,  `eventEndDatum` varchar(10) NOT NULL,  `eventStartZeit` varchar(5) NOT NULL,  `eventText` text NOT NULL,  `eventAnzahlTeilnehmer` int(11) NOT NULL,  `eventBegleitung` int(11) NOT NULL,  `zusatz` varchar(255) NOT NULL,  `zusatz2` varchar(255) NOT NULL,  PRIMARY KEY (`eventid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
DROP TABLE `morp_fa`;
CREATE TABLE `morp_fa` (  `faid` int(11) NOT NULL AUTO_INCREMENT,  `fa` varchar(30) NOT NULL,  `beschreibung` varchar(100) NOT NULL,  PRIMARY KEY (`faid`)) ENGINE=MyISAM AUTO_INCREMENT=348 DEFAULT CHARSET=latin1;
INSERT INTO `morp_fa` VALUES('1', 'fa-clock-o', '_ Uhr');
INSERT INTO `morp_fa` VALUES('2', 'fa-star', '_ stern');
INSERT INTO `morp_fa` VALUES('3', 'fa-cutlery', 'messer gabel');
INSERT INTO `morp_fa` VALUES('4', 'fa-camera', '_ camera');
INSERT INTO `morp_fa` VALUES('5', 'fa-camera-retro', '_ camera-retro');
INSERT INTO `morp_fa` VALUES('6', 'fa-desktop', 'bildschirm');
INSERT INTO `morp_fa` VALUES('7', 'fa-adjust', 'adjust');
INSERT INTO `morp_fa` VALUES('8', 'fa-anchor', 'anchor');
INSERT INTO `morp_fa` VALUES('9', 'fa-archive', 'archive');
INSERT INTO `morp_fa` VALUES('10', 'fa-area-chart', 'area-chart');
INSERT INTO `morp_fa` VALUES('11', 'fa-arrows', 'arrows');
INSERT INTO `morp_fa` VALUES('12', 'fa-arrows-h', 'arrows-h');
INSERT INTO `morp_fa` VALUES('13', 'fa-arrows-v', 'arrows-v');
INSERT INTO `morp_fa` VALUES('14', 'fa-asterisk', 'asterisk');
INSERT INTO `morp_fa` VALUES('15', 'fa-at', 'at');
INSERT INTO `morp_fa` VALUES('16', 'fa-automobile', 'automobile');
INSERT INTO `morp_fa` VALUES('17', 'fa-ban', 'ban');
INSERT INTO `morp_fa` VALUES('18', 'fa-bank', 'bank');
INSERT INTO `morp_fa` VALUES('19', 'fa-bar-chart', 'bar-chart');
INSERT INTO `morp_fa` VALUES('20', 'fa-bar-chart-o', 'bar-chart-o');
INSERT INTO `morp_fa` VALUES('21', 'fa-barcode', 'barcode');
INSERT INTO `morp_fa` VALUES('22', 'fa-bars', 'bars');
INSERT INTO `morp_fa` VALUES('23', 'fa-bed', 'bed');
INSERT INTO `morp_fa` VALUES('24', 'fa-beer', 'beer');
INSERT INTO `morp_fa` VALUES('25', 'fa-bell', 'bell');
INSERT INTO `morp_fa` VALUES('26', 'fa-bell-o', 'bell-o');
INSERT INTO `morp_fa` VALUES('27', 'fa-bell-slash', 'bell-slash');
INSERT INTO `morp_fa` VALUES('28', 'fa-bell-slash-o', 'bell-slash-o');
INSERT INTO `morp_fa` VALUES('29', 'fa-bicycle', 'bicycle');
INSERT INTO `morp_fa` VALUES('30', 'fa-binoculars', 'binoculars');
INSERT INTO `morp_fa` VALUES('31', 'fa-birthday-cake', 'birthday-cake');
INSERT INTO `morp_fa` VALUES('32', 'fa-bolt', 'bolt');
INSERT INTO `morp_fa` VALUES('33', 'fa-bomb', 'bomb');
INSERT INTO `morp_fa` VALUES('34', 'fa-book', 'book');
INSERT INTO `morp_fa` VALUES('35', 'fa-bookmark', 'bookmark');
INSERT INTO `morp_fa` VALUES('36', 'fa-bookmark-o', 'bookmark-o');
INSERT INTO `morp_fa` VALUES('37', 'fa-briefcase', 'briefcase');
INSERT INTO `morp_fa` VALUES('38', 'fa-bug', 'bug');
INSERT INTO `morp_fa` VALUES('39', 'fa-building', 'building');
INSERT INTO `morp_fa` VALUES('40', 'fa-building-o', 'building-o');
INSERT INTO `morp_fa` VALUES('41', 'fa-bullhorn', 'bullhorn');
INSERT INTO `morp_fa` VALUES('42', 'fa-bullseye', 'bullseye');
INSERT INTO `morp_fa` VALUES('43', 'fa-bus', 'bus');
INSERT INTO `morp_fa` VALUES('44', 'fa-cab', 'cab');
INSERT INTO `morp_fa` VALUES('45', 'fa-calculator', 'calculator');
INSERT INTO `morp_fa` VALUES('46', 'fa-calendar', 'calendar');
INSERT INTO `morp_fa` VALUES('47', 'fa-calendar-o', 'calendar-o');
INSERT INTO `morp_fa` VALUES('48', 'fa-camera', 'camera');
INSERT INTO `morp_fa` VALUES('49', 'fa-camera-retro', 'camera-retro');
INSERT INTO `morp_fa` VALUES('50', 'fa-car', 'car');
INSERT INTO `morp_fa` VALUES('54', 'fa-caret-square-o-up', 'caret-square-o-up');
INSERT INTO `morp_fa` VALUES('55', 'fa-cart-arrow-down', 'cart-arrow-down');
INSERT INTO `morp_fa` VALUES('56', 'fa-cart-plus', 'cart-plus');
INSERT INTO `morp_fa` VALUES('57', 'fa-cc', 'cc');
INSERT INTO `morp_fa` VALUES('58', 'fa-certificate', 'certificate');
INSERT INTO `morp_fa` VALUES('59', 'fa-check', 'check');
INSERT INTO `morp_fa` VALUES('60', 'fa-check-circle', 'check-circle');
INSERT INTO `morp_fa` VALUES('61', 'fa-check-circle-o', 'check-circle-o');
INSERT INTO `morp_fa` VALUES('62', 'fa-check-square', 'check-square');
INSERT INTO `morp_fa` VALUES('63', 'fa-check-square-o', 'check');
INSERT INTO `morp_fa` VALUES('64', 'fa-child', 'child');
INSERT INTO `morp_fa` VALUES('65', 'fa-circle', 'circle');
INSERT INTO `morp_fa` VALUES('66', 'fa-circle-o', 'circle-o');
INSERT INTO `morp_fa` VALUES('67', 'fa-circle-o-notch', 'circle-o-notch');
INSERT INTO `morp_fa` VALUES('68', 'fa-circle-thin', 'circle-thin');
INSERT INTO `morp_fa` VALUES('69', 'fa-clock-o', 'clock-o');
INSERT INTO `morp_fa` VALUES('70', 'fa-close', 'close');
INSERT INTO `morp_fa` VALUES('71', 'fa-cloud', 'cloud');
INSERT INTO `morp_fa` VALUES('72', 'fa-cloud-download', 'cloud-download');
INSERT INTO `morp_fa` VALUES('73', 'fa-cloud-upload', 'cloud-upload');
INSERT INTO `morp_fa` VALUES('74', 'fa-code', 'code');
INSERT INTO `morp_fa` VALUES('75', 'fa-code-fork', 'code-fork');
INSERT INTO `morp_fa` VALUES('76', 'fa-coffee', 'coffee');
INSERT INTO `morp_fa` VALUES('77', 'fa-cog', 'cog');
INSERT INTO `morp_fa` VALUES('78', 'fa-cogs', 'cogs');
INSERT INTO `morp_fa` VALUES('79', 'fa-comment', 'sprechblase');
INSERT INTO `morp_fa` VALUES('80', 'fa-comment-o', 'comment-o');
INSERT INTO `morp_fa` VALUES('81', 'fa-comments', 'comments');
INSERT INTO `morp_fa` VALUES('82', 'fa-comments-o', 'comments-o');
INSERT INTO `morp_fa` VALUES('83', 'fa-compass', 'compass');
INSERT INTO `morp_fa` VALUES('84', 'fa-copyright', 'copyright');
INSERT INTO `morp_fa` VALUES('85', 'fa-credit-card', 'credit-card');
INSERT INTO `morp_fa` VALUES('86', 'fa-crop', 'crop');
INSERT INTO `morp_fa` VALUES('87', 'fa-crosshairs', 'crosshairs');
INSERT INTO `morp_fa` VALUES('88', 'fa-cube', 'cube');
INSERT INTO `morp_fa` VALUES('89', 'fa-cubes', 'cubes');
INSERT INTO `morp_fa` VALUES('90', 'fa-cutlery', 'cutlery');
INSERT INTO `morp_fa` VALUES('91', 'fa-dashboard', 'dashboard');
INSERT INTO `morp_fa` VALUES('92', 'fa-database', 'database');
INSERT INTO `morp_fa` VALUES('93', 'fa-desktop', 'desktop');
INSERT INTO `morp_fa` VALUES('94', 'fa-diamond', 'diamond');
INSERT INTO `morp_fa` VALUES('95', 'fa-dot-circle-o', 'dot-circle-o');
INSERT INTO `morp_fa` VALUES('96', 'fa-download', 'download');
INSERT INTO `morp_fa` VALUES('97', 'fa-edit', 'edit');
INSERT INTO `morp_fa` VALUES('98', 'fa-ellipsis-h', 'ellipsis-h');
INSERT INTO `morp_fa` VALUES('99', 'fa-ellipsis-v', 'ellipsis-v');
INSERT INTO `morp_fa` VALUES('100', 'fa-envelope', 'envelope');
INSERT INTO `morp_fa` VALUES('101', 'fa-envelope-o', 'envelope-o');
INSERT INTO `morp_fa` VALUES('102', 'fa-envelope-square', 'envelope-square');
INSERT INTO `morp_fa` VALUES('103', 'fa-eraser', 'eraser');
INSERT INTO `morp_fa` VALUES('104', 'fa-exchange', 'exchange');
INSERT INTO `morp_fa` VALUES('105', 'fa-exclamation', 'exclamation');
INSERT INTO `morp_fa` VALUES('339', 'fa-twitter', 'twitter');
INSERT INTO `morp_fa` VALUES('108', 'fa-external-link', 'external-link');
INSERT INTO `morp_fa` VALUES('110', 'fa-eye', 'Eye');
INSERT INTO `morp_fa` VALUES('111', 'fa-eye-slash', 'eye-slash');
INSERT INTO `morp_fa` VALUES('112', 'fa-eyedropper', 'eyedropper');
INSERT INTO `morp_fa` VALUES('113', 'fa-fax', 'fax');
INSERT INTO `morp_fa` VALUES('114', 'fa-female', 'female');
INSERT INTO `morp_fa` VALUES('115', 'fa-fighter-jet', 'fighter-jet');
INSERT INTO `morp_fa` VALUES('116', 'fa-file-archive-o', 'file-archive-o');
INSERT INTO `morp_fa` VALUES('117', 'fa-file-audio-o', 'file-audio-o');
INSERT INTO `morp_fa` VALUES('118', 'fa-file-code-o', 'file-code-o');
INSERT INTO `morp_fa` VALUES('119', 'fa-file-excel-o', 'file-excel-o');
INSERT INTO `morp_fa` VALUES('120', 'fa-file-image-o', 'file-image-o');
INSERT INTO `morp_fa` VALUES('121', 'fa-file-movie-o', 'file-movie-o');
INSERT INTO `morp_fa` VALUES('122', 'fa-file-pdf-o', 'file-pdf-o');
INSERT INTO `morp_fa` VALUES('123', 'fa-file-photo-o', 'file-photo-o');
INSERT INTO `morp_fa` VALUES('124', 'fa-file-picture-o', 'file-picture-o');
INSERT INTO `morp_fa` VALUES('125', 'fa-file-powerpoint-o', 'file-powerpoint-o');
INSERT INTO `morp_fa` VALUES('126', 'fa-file-sound-o', 'file-sound-o');
INSERT INTO `morp_fa` VALUES('127', 'fa-file-video-o', 'file-video-o');
INSERT INTO `morp_fa` VALUES('128', 'fa-file-word-o', 'file-word-o');
INSERT INTO `morp_fa` VALUES('129', 'fa-file-zip-o', 'file-zip-o');
INSERT INTO `morp_fa` VALUES('130', 'fa-film', 'film');
INSERT INTO `morp_fa` VALUES('131', 'fa-filter', 'filter');
INSERT INTO `morp_fa` VALUES('132', 'fa-fire', 'fire');
INSERT INTO `morp_fa` VALUES('133', 'fa-fire-extinguisher', 'fire-extinguisher');
INSERT INTO `morp_fa` VALUES('134', 'fa-flag', 'flag');
INSERT INTO `morp_fa` VALUES('135', 'fa-flag-checkered', 'flag-checkered');
INSERT INTO `morp_fa` VALUES('136', 'fa-flag-o', 'flag-o');
INSERT INTO `morp_fa` VALUES('137', 'fa-flash', 'flash');
INSERT INTO `morp_fa` VALUES('138', 'fa-flask', 'flask');
INSERT INTO `morp_fa` VALUES('139', 'fa-folder', 'folder');
INSERT INTO `morp_fa` VALUES('140', 'fa-folder-o', 'folder-o');
INSERT INTO `morp_fa` VALUES('141', 'fa-folder-open', 'folder-open');
INSERT INTO `morp_fa` VALUES('142', 'fa-folder-open-o', 'folder-open-o');
INSERT INTO `morp_fa` VALUES('143', 'fa-frown-o', 'frown-o');
INSERT INTO `morp_fa` VALUES('144', 'fa-futbol-o', 'futbol-o');
INSERT INTO `morp_fa` VALUES('145', 'fa-gamepad', 'gamepad');
INSERT INTO `morp_fa` VALUES('146', 'fa-gavel', 'gavel');
INSERT INTO `morp_fa` VALUES('147', 'fa-gear', 'gear');
INSERT INTO `morp_fa` VALUES('148', 'fa-gears', 'gears');
INSERT INTO `morp_fa` VALUES('149', 'fa-genderless', 'genderless');
INSERT INTO `morp_fa` VALUES('150', 'fa-gift', 'gift');
INSERT INTO `morp_fa` VALUES('151', 'fa-glass', 'glass');
INSERT INTO `morp_fa` VALUES('152', 'fa-globe', 'globe');
INSERT INTO `morp_fa` VALUES('153', 'fa-graduation-cap', 'graduation-cap');
INSERT INTO `morp_fa` VALUES('154', 'fa-group', 'group');
INSERT INTO `morp_fa` VALUES('155', 'fa-hdd-o', 'hdd-o');
INSERT INTO `morp_fa` VALUES('156', 'fa-headphones', 'headphones');
INSERT INTO `morp_fa` VALUES('157', 'fa-heart', 'heart');
INSERT INTO `morp_fa` VALUES('158', 'fa-heart-o', 'heart-o');
INSERT INTO `morp_fa` VALUES('159', 'fa-heartbeat', 'heartbeat');
INSERT INTO `morp_fa` VALUES('160', 'fa-history', 'history');
INSERT INTO `morp_fa` VALUES('161', 'fa-home', 'home');
INSERT INTO `morp_fa` VALUES('162', 'fa-hotel', 'hotel');
INSERT INTO `morp_fa` VALUES('163', 'fa-image', 'image');
INSERT INTO `morp_fa` VALUES('164', 'fa-inbox', 'inbox');
INSERT INTO `morp_fa` VALUES('165', 'fa-info', 'info');
INSERT INTO `morp_fa` VALUES('166', 'fa-info-circle', 'info-circle');
INSERT INTO `morp_fa` VALUES('167', 'fa-institution', 'institution');
INSERT INTO `morp_fa` VALUES('168', 'fa-key', 'key');
INSERT INTO `morp_fa` VALUES('169', 'fa-keyboard-o', 'keyboard-o');
INSERT INTO `morp_fa` VALUES('170', 'fa-language', 'language');
INSERT INTO `morp_fa` VALUES('171', 'fa-laptop', 'laptop');
INSERT INTO `morp_fa` VALUES('172', 'fa-leaf', 'Blatt');
INSERT INTO `morp_fa` VALUES('173', 'fa-legal', 'legal');
INSERT INTO `morp_fa` VALUES('174', 'fa-lemon-o', 'lemon-o');
INSERT INTO `morp_fa` VALUES('175', 'fa-level-down', 'level-down');
INSERT INTO `morp_fa` VALUES('176', 'fa-level-up', 'level-up');
INSERT INTO `morp_fa` VALUES('177', 'fa-life-bouy', 'life-bouy');
INSERT INTO `morp_fa` VALUES('178', 'fa-life-buoy', 'life-buoy');
INSERT INTO `morp_fa` VALUES('179', 'fa-life-ring', 'life-ring');
INSERT INTO `morp_fa` VALUES('180', 'fa-life-saver', 'life-saver');
INSERT INTO `morp_fa` VALUES('181', 'fa-lightbulb-o', 'lightbulb-o');
INSERT INTO `morp_fa` VALUES('182', 'fa-line-chart', 'line-chart');
INSERT INTO `morp_fa` VALUES('183', 'fa-location-arrow', 'location-arrow');
INSERT INTO `morp_fa` VALUES('184', 'fa-lock', 'lock');
INSERT INTO `morp_fa` VALUES('185', 'fa-magic', 'magic');
INSERT INTO `morp_fa` VALUES('186', 'fa-magnet', 'magnet');
INSERT INTO `morp_fa` VALUES('187', 'fa-mail-forward', 'mail-forward');
INSERT INTO `morp_fa` VALUES('188', 'fa-mail-reply', 'mail-reply');
INSERT INTO `morp_fa` VALUES('189', 'fa-mail-reply-all', 'mail-reply-all');
INSERT INTO `morp_fa` VALUES('190', 'fa-male', 'male');
INSERT INTO `morp_fa` VALUES('191', 'fa-map-marker', 'map-marker');
INSERT INTO `morp_fa` VALUES('192', 'fa-meh-o', 'meh-o');
INSERT INTO `morp_fa` VALUES('193', 'fa-microphone', 'microphone');
INSERT INTO `morp_fa` VALUES('194', 'fa-microphone-slash', 'microphone-slash');
INSERT INTO `morp_fa` VALUES('195', 'fa-minus', 'minus');
INSERT INTO `morp_fa` VALUES('196', 'fa-minus-circle', 'minus-circle');
INSERT INTO `morp_fa` VALUES('197', 'fa-minus-square', 'minus-square');
INSERT INTO `morp_fa` VALUES('198', 'fa-minus-square-o', 'minus-square-o');
INSERT INTO `morp_fa` VALUES('199', 'fa-mobile', 'mobile');
INSERT INTO `morp_fa` VALUES('200', 'fa-mobile-phone', 'mobile-phone');
INSERT INTO `morp_fa` VALUES('201', 'fa-money', 'money');
INSERT INTO `morp_fa` VALUES('202', 'fa-moon-o', 'moon-o');
INSERT INTO `morp_fa` VALUES('203', 'fa-mortar-board', 'mortar-board');
INSERT INTO `morp_fa` VALUES('204', 'fa-motorcycle', 'motorcycle');
INSERT INTO `morp_fa` VALUES('205', 'fa-music', 'music');
INSERT INTO `morp_fa` VALUES('206', 'fa-navicon', 'navicon');
INSERT INTO `morp_fa` VALUES('207', 'fa-newspaper-o', 'newspaper-o');
INSERT INTO `morp_fa` VALUES('208', 'fa-paint-brush', 'paint-brush');
INSERT INTO `morp_fa` VALUES('209', 'fa-paper-plane', 'paper-plane');
INSERT INTO `morp_fa` VALUES('210', 'fa-paper-plane-o', 'felix paper-plane-o');
INSERT INTO `morp_fa` VALUES('211', 'fa-paw', 'paw');
INSERT INTO `morp_fa` VALUES('212', 'fa-pencil', 'pencil');
INSERT INTO `morp_fa` VALUES('213', 'fa-pencil-square', 'pencil-square');
INSERT INTO `morp_fa` VALUES('214', 'fa-pencil-square-o', 'pencil-square-o');
INSERT INTO `morp_fa` VALUES('215', 'fa-phone', 'phone');
INSERT INTO `morp_fa` VALUES('216', 'fa-phone-square', 'phone-square');
INSERT INTO `morp_fa` VALUES('217', 'fa-photo', 'photo');
INSERT INTO `morp_fa` VALUES('218', 'fa-picture-o', 'picture-o');
INSERT INTO `morp_fa` VALUES('219', 'fa-pie-chart', 'pie-chart');
INSERT INTO `morp_fa` VALUES('220', 'fa-plane', 'plane');
INSERT INTO `morp_fa` VALUES('221', 'fa-plug', 'plug');
INSERT INTO `morp_fa` VALUES('222', 'fa-plus', 'plus');
INSERT INTO `morp_fa` VALUES('223', 'fa-plus-circle', 'plus-circle');
INSERT INTO `morp_fa` VALUES('224', 'fa-plus-square', 'plus-square');
INSERT INTO `morp_fa` VALUES('225', 'fa-plus-square-o', 'plus-square-o');
INSERT INTO `morp_fa` VALUES('226', 'fa-power-off', 'power-off');
INSERT INTO `morp_fa` VALUES('227', 'fa-print', 'print');
INSERT INTO `morp_fa` VALUES('228', 'fa-puzzle-piece', 'puzzle-piece');
INSERT INTO `morp_fa` VALUES('229', 'fa-qrcode', 'qrcode');
INSERT INTO `morp_fa` VALUES('230', 'fa-question', 'question');
INSERT INTO `morp_fa` VALUES('231', 'fa-question-circle', 'question-circle');
INSERT INTO `morp_fa` VALUES('232', 'fa-quote-left', 'quote-left');
INSERT INTO `morp_fa` VALUES('233', 'fa-quote-right', 'quote-right');
INSERT INTO `morp_fa` VALUES('234', 'fa-random', 'random');
INSERT INTO `morp_fa` VALUES('235', 'fa-recycle', 'recycle');
INSERT INTO `morp_fa` VALUES('236', 'fa-refresh', 'refresh');
INSERT INTO `morp_fa` VALUES('237', 'fa-remove', 'remove');
INSERT INTO `morp_fa` VALUES('238', 'fa-reorder', 'reorder');
INSERT INTO `morp_fa` VALUES('239', 'fa-reply', 'reply');
INSERT INTO `morp_fa` VALUES('240', 'fa-reply-all', 'reply-all');
INSERT INTO `morp_fa` VALUES('241', 'fa-retweet', 'retweet');
INSERT INTO `morp_fa` VALUES('242', 'fa-road', 'road');
INSERT INTO `morp_fa` VALUES('243', 'fa-rocket', 'rocket');
INSERT INTO `morp_fa` VALUES('244', 'fa-rss', 'rss');
INSERT INTO `morp_fa` VALUES('245', 'fa-rss-square', 'rss-square');
INSERT INTO `morp_fa` VALUES('246', 'fa-search', 'search');
INSERT INTO `morp_fa` VALUES('247', 'fa-search-minus', 'search-minus');
INSERT INTO `morp_fa` VALUES('248', 'fa-search-plus', 'search-plus');
INSERT INTO `morp_fa` VALUES('249', 'fa-send', 'send');
INSERT INTO `morp_fa` VALUES('250', 'fa-send-o', 'send-o');
INSERT INTO `morp_fa` VALUES('251', 'fa-server', 'server');
INSERT INTO `morp_fa` VALUES('252', 'fa-share', 'share');
INSERT INTO `morp_fa` VALUES('253', 'fa-share-alt', 'share-alt');
INSERT INTO `morp_fa` VALUES('254', 'fa-share-alt-square', 'share-alt-square');
INSERT INTO `morp_fa` VALUES('255', 'fa-share-square', 'share-square');
INSERT INTO `morp_fa` VALUES('256', 'fa-share-square-o', 'share-square-o');
INSERT INTO `morp_fa` VALUES('257', 'fa-shield', 'shield');
INSERT INTO `morp_fa` VALUES('258', 'fa-ship', 'ship');
INSERT INTO `morp_fa` VALUES('259', 'fa-shopping-cart', 'shopping-cart');
INSERT INTO `morp_fa` VALUES('260', 'fa-sign-in', 'sign-in');
INSERT INTO `morp_fa` VALUES('261', 'fa-sign-out', 'sign-out');
INSERT INTO `morp_fa` VALUES('262', 'fa-signal', 'signal');
INSERT INTO `morp_fa` VALUES('263', 'fa-sitemap', 'sitemap');
INSERT INTO `morp_fa` VALUES('264', 'fa-sliders', 'sliders');
INSERT INTO `morp_fa` VALUES('265', 'fa-smile-o', 'smile-o');
INSERT INTO `morp_fa` VALUES('266', 'fa-soccer-ball-o', 'soccer-ball-o');
INSERT INTO `morp_fa` VALUES('267', 'fa-sort', 'sort');
INSERT INTO `morp_fa` VALUES('268', 'fa-sort-alpha-asc', 'sort-alpha-asc');
INSERT INTO `morp_fa` VALUES('269', 'fa-sort-alpha-desc', 'sort-alpha-desc');
INSERT INTO `morp_fa` VALUES('270', 'fa-sort-amount-asc', 'sort-amount-asc');
INSERT INTO `morp_fa` VALUES('271', 'fa-sort-amount-desc', 'sort-amount-desc');
INSERT INTO `morp_fa` VALUES('272', 'fa-sort-asc', 'sort-asc');
INSERT INTO `morp_fa` VALUES('273', 'fa-sort-desc', 'sort-desc');
INSERT INTO `morp_fa` VALUES('274', 'fa-sort-down', 'sort-down');
INSERT INTO `morp_fa` VALUES('275', 'fa-sort-numeric-asc', 'sort-numeric-asc');
INSERT INTO `morp_fa` VALUES('276', 'fa-sort-numeric-desc', 'sort-numeric-desc');
INSERT INTO `morp_fa` VALUES('277', 'fa-sort-up', 'sort-up');
INSERT INTO `morp_fa` VALUES('278', 'fa-space-shuttle', 'space-shuttle');
INSERT INTO `morp_fa` VALUES('279', 'fa-spinner', 'spinner');
INSERT INTO `morp_fa` VALUES('280', 'fa-spoon', 'spoon');
INSERT INTO `morp_fa` VALUES('281', 'fa-square', 'square');
INSERT INTO `morp_fa` VALUES('282', 'fa-square-o', 'square-o');
INSERT INTO `morp_fa` VALUES('283', 'fa-star', 'stern');
INSERT INTO `morp_fa` VALUES('284', 'fa-star-half', 'star-half');
INSERT INTO `morp_fa` VALUES('285', 'fa-star-half-empty', 'star-half-empty');
INSERT INTO `morp_fa` VALUES('286', 'fa-star-half-full', 'star-half-full');
INSERT INTO `morp_fa` VALUES('287', 'fa-star-half-o', 'star-half-o');
INSERT INTO `morp_fa` VALUES('288', 'fa-star-o', 'star-o');
INSERT INTO `morp_fa` VALUES('289', 'fa-street-view', 'street-view');
INSERT INTO `morp_fa` VALUES('290', 'fa-suitcase', 'suitcase');
INSERT INTO `morp_fa` VALUES('291', 'fa-support', 'support');
INSERT INTO `morp_fa` VALUES('292', 'fa-tachometer', 'tachometer');
INSERT INTO `morp_fa` VALUES('293', 'fa-tag', 'tag');
INSERT INTO `morp_fa` VALUES('294', 'fa-tags', 'tags');
INSERT INTO `morp_fa` VALUES('295', 'fa-tasks', 'tasks');
INSERT INTO `morp_fa` VALUES('296', 'fa-taxi', 'taxi');
INSERT INTO `morp_fa` VALUES('297', 'fa-terminal', 'terminal');
INSERT INTO `morp_fa` VALUES('298', 'fa-thumb-tack', 'thumb-tack');
INSERT INTO `morp_fa` VALUES('299', 'fa-thumbs-down', 'thumbs-down');
INSERT INTO `morp_fa` VALUES('300', 'fa-thumbs-o-down', 'thumbs-o-down');
INSERT INTO `morp_fa` VALUES('301', 'fa-thumbs-o-up', 'thumbs-o-up');
INSERT INTO `morp_fa` VALUES('302', 'fa-thumbs-up', 'Finger up');
INSERT INTO `morp_fa` VALUES('303', 'fa-ticket', 'ticket');
INSERT INTO `morp_fa` VALUES('304', 'fa-times', 'times');
INSERT INTO `morp_fa` VALUES('305', 'fa-times-circle', 'times-circle');
INSERT INTO `morp_fa` VALUES('306', 'fa-times-circle-o', 'times-circle-o');
INSERT INTO `morp_fa` VALUES('307', 'fa-tint', 'tint');
INSERT INTO `morp_fa` VALUES('308', 'fa-toggle-down', 'toggle-down');
INSERT INTO `morp_fa` VALUES('309', 'fa-toggle-left', 'toggle-left');
INSERT INTO `morp_fa` VALUES('310', 'fa-toggle-off', 'toggle-off');
INSERT INTO `morp_fa` VALUES('311', 'fa-toggle-on', 'toggle-on');
INSERT INTO `morp_fa` VALUES('312', 'fa-toggle-right', 'toggle-right');
INSERT INTO `morp_fa` VALUES('313', 'fa-toggle-up', 'toggle-up');
INSERT INTO `morp_fa` VALUES('314', 'fa-trash', 'trash');
INSERT INTO `morp_fa` VALUES('315', 'fa-trash-o', 'trash-o');
INSERT INTO `morp_fa` VALUES('316', 'fa-tree', 'tree');
INSERT INTO `morp_fa` VALUES('317', 'fa-trophy', 'trophy');
INSERT INTO `morp_fa` VALUES('318', 'fa-truck', 'truck');
INSERT INTO `morp_fa` VALUES('319', 'fa-tty', 'tty');
INSERT INTO `morp_fa` VALUES('320', 'fa-umbrella', 'umbrella');
INSERT INTO `morp_fa` VALUES('321', 'fa-university', 'university');
INSERT INTO `morp_fa` VALUES('322', 'fa-unlock', 'unlock');
INSERT INTO `morp_fa` VALUES('323', 'fa-unlock-alt', 'unlock-alt');
INSERT INTO `morp_fa` VALUES('324', 'fa-unsorted', 'unsorted');
INSERT INTO `morp_fa` VALUES('325', 'fa-upload', 'upload');
INSERT INTO `morp_fa` VALUES('326', 'fa-user', 'user');
INSERT INTO `morp_fa` VALUES('327', 'fa-user-plus', 'user-plus');
INSERT INTO `morp_fa` VALUES('328', 'fa-user-secret', 'user-secret');
INSERT INTO `morp_fa` VALUES('329', 'fa-user-times', 'user-times');
INSERT INTO `morp_fa` VALUES('330', 'fa-users', 'User');
INSERT INTO `morp_fa` VALUES('331', 'fa-video-camera', 'video-camera');
INSERT INTO `morp_fa` VALUES('332', 'fa-volume-down', 'volume-down');
INSERT INTO `morp_fa` VALUES('333', 'fa-volume-off', 'volume-off');
INSERT INTO `morp_fa` VALUES('334', 'fa-volume-up', 'volume-up');
INSERT INTO `morp_fa` VALUES('335', 'fa-warning', 'warning');
INSERT INTO `morp_fa` VALUES('336', 'fa-wheelchair', 'wheelchair');
INSERT INTO `morp_fa` VALUES('337', 'fa-wifi', 'wifi');
INSERT INTO `morp_fa` VALUES('338', 'fa-wrench', 'wrench');
INSERT INTO `morp_fa` VALUES('341', 'fa-xing', 'xing');
INSERT INTO `morp_fa` VALUES('342', ' fa-xing-square', 'xing 2');
INSERT INTO `morp_fa` VALUES('344', 'fa-facebook', ' agis facebook');
INSERT INTO `morp_fa` VALUES('345', 'fa-handshake-o', 'handshake-o');
INSERT INTO `morp_fa` VALUES('346', 'fa-volume-control-phone', 'volume-control-phone');
INSERT INTO `morp_fa` VALUES('347', 'fa-th', 'Inklusion');
DROP TABLE `morp_intranet_user`;
CREATE TABLE `morp_intranet_user` (  `mid` int(11) NOT NULL AUTO_INCREMENT,  `uname` varchar(100) NOT NULL,  `nname` varchar(100) NOT NULL,  `vname` varchar(100) NOT NULL,  `anrede` varchar(10) NOT NULL,  `pw` varchar(100) NOT NULL,  `admin` int(1) NOT NULL DEFAULT '0',  `fon` varchar(100) NOT NULL,  `email` varchar(100) NOT NULL,  `img` varchar(255) NOT NULL,  `kontrolle` int(11) NOT NULL,  `pass` varchar(255) NOT NULL,  `newpass` int(11) NOT NULL,  `countLogins` int(11) NOT NULL,  `setMeFree` varchar(10) NOT NULL DEFAULT '#k8uNjj',  `abteilung` int(11) NOT NULL,  `wantEmail` int(11) NOT NULL,  `secure` varchar(255) NOT NULL,  PRIMARY KEY (`mid`),  UNIQUE KEY `uname` (`uname`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_intranet_user_track`;
CREATE TABLE `morp_intranet_user_track` (  `trackID` int(11) NOT NULL AUTO_INCREMENT,  `mid` int(11) NOT NULL,  `datum` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  PRIMARY KEY (`trackID`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_mitarbeiter`;
CREATE TABLE `morp_mitarbeiter` (  `mid` int(11) NOT NULL AUTO_INCREMENT,  `aid` int(11) NOT NULL,  `name` varchar(100) NOT NULL,  `vorname` varchar(100) NOT NULL,  `position` varchar(255) NOT NULL,  `beschreibung` text NOT NULL,  `email` varchar(50) NOT NULL,  `fon` varchar(20) NOT NULL,  `img1` varchar(100) NOT NULL,  `img2` varchar(100) NOT NULL,  `img3` varchar(100) NOT NULL,  `reihenfolge` int(11) NOT NULL DEFAULT '10',  `sichtbar` int(1) NOT NULL,  `strasse` varchar(100) NOT NULL,  `plz` varchar(10) NOT NULL,  `ort` varchar(100) NOT NULL,  `tel` varchar(100) NOT NULL,  `www` varchar(100) NOT NULL,  `frt` varchar(100) NOT NULL,  `et` varchar(100) NOT NULL,  `et1` varchar(100) NOT NULL,  `et2` varchar(100) NOT NULL,  `et3` varchar(100) NOT NULL,  `et4` varchar(100) NOT NULL,  `et5` varchar(100) NOT NULL,  `et6` varchar(100) NOT NULL,  `ipb` varchar(100) NOT NULL,  `ipb1` varchar(100) NOT NULL,  `ipb2` varchar(100) NOT NULL,  `ipb3` varchar(100) NOT NULL,  `ipb4` varchar(100) NOT NULL,  `ipb5` varchar(100) NOT NULL,  `jugend` int(1) NOT NULL,  `kinder` int(1) NOT NULL,  `coaching` int(1) NOT NULL,  `teamcoaching` int(1) NOT NULL,  `liste` int(1) NOT NULL DEFAULT '1',  `land` int(1) NOT NULL DEFAULT '1',  `freitext` text NOT NULL,  PRIMARY KEY (`mid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
DROP TABLE `morp_settings`;
CREATE TABLE `morp_settings` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` varchar(50) NOT NULL,  `var` varchar(20) NOT NULL,  `value` text NOT NULL,  `reihenfolge` int(11) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;
INSERT INTO `morp_settings` VALUES('1', 'E-Mail Kunde / email Client', 'email', 'bk@pixel-dusche.de', '3');
INSERT INTO `morp_settings` VALUES('2', 'E-Mail Name', 'emailname', 'Praxis Christian Skurnia', '2');
INSERT INTO `morp_settings` VALUES('3', 'Kunde / Client', 'client', 'Praxis Christian Skurnia', '1');
INSERT INTO `morp_settings` VALUES('5', 'Author', 'author', 'Bjoern Knetter, CMS Morpheus', '4');
INSERT INTO `morp_settings` VALUES('6', 'Adresse komplett', 'vcard', 'Praxis Christian Skurnia\nWiesbadener Straße 20\n65719 Hofheim am Taunus\nTelefon: 06122 4333\n', '0');
INSERT INTO `morp_settings` VALUES('7', 'copyright', 'copyr', 'copyright 2019 by Praxis Christian Skurnia', '0');
DROP TABLE `morp_settings_css`;
CREATE TABLE `morp_settings_css` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` varchar(50) NOT NULL,  `value` varchar(255) NOT NULL,  `reihenfolge` int(11) NOT NULL,  `className` varchar(255) NOT NULL,  `classVal` varchar(20) NOT NULL,  `fontID` int(11) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE `morp_settings_fonts`;
CREATE TABLE `morp_settings_fonts` (  `fontID` int(11) NOT NULL AUTO_INCREMENT,  `name` varchar(50) NOT NULL,  `fontClass` varchar(30) NOT NULL,  `fontWeight` varchar(10) NOT NULL,  `sichtbar` int(1) NOT NULL,  `reihenfolge` int(11) NOT NULL,  `value` text NOT NULL,  PRIMARY KEY (`fontID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE `morp_sprachdatei`;
CREATE TABLE `morp_sprachdatei` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `de` text COLLATE utf8_unicode_ci NOT NULL,  `us` text COLLATE utf8_unicode_ci NOT NULL,  `en` text COLLATE utf8_unicode_ci NOT NULL,  `ru` text COLLATE utf8_unicode_ci NOT NULL,  `es` text COLLATE utf8_unicode_ci NOT NULL,  `dk` text COLLATE utf8_unicode_ci NOT NULL,  `bez` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `fr` text COLLATE utf8_unicode_ci NOT NULL,  `it` text COLLATE utf8_unicode_ci NOT NULL,  KEY `id` (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_suche_count`;
CREATE TABLE `morp_suche_count` (  `sid` int(11) NOT NULL AUTO_INCREMENT,  `kid` int(11) NOT NULL DEFAULT '0',  `navid` int(11) NOT NULL DEFAULT '0',  `anzde` int(11) NOT NULL DEFAULT '0',  `anzen` int(11) NOT NULL DEFAULT '0',  `art` int(1) NOT NULL DEFAULT '1',  `stid` int(11) NOT NULL DEFAULT '0',  `nid` int(11) NOT NULL,  `ngid` int(11) NOT NULL,  PRIMARY KEY (`sid`),  UNIQUE KEY `kid` (`kid`,`navid`,`art`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_suche_keyw`;
CREATE TABLE `morp_suche_keyw` (  `keyw` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `de` int(1) NOT NULL DEFAULT '0',  `en` int(1) NOT NULL DEFAULT '0',  `fr` int(1) NOT NULL,  `ru` int(1) NOT NULL,  `it` int(1) NOT NULL,  `es` int(1) NOT NULL,  `desc` int(1) NOT NULL DEFAULT '0',  `title` int(1) NOT NULL DEFAULT '0',  `news` int(1) NOT NULL DEFAULT '0',  `table` varchar(30) COLLATE utf8_unicode_ci NOT NULL,  `kid` int(11) NOT NULL AUTO_INCREMENT,  PRIMARY KEY (`kid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
DROP TABLE `morp_suche_track`;
CREATE TABLE `morp_suche_track` (  `ms` int(11) NOT NULL AUTO_INCREMENT,  `suche` varchar(255) NOT NULL,  `time` varchar(20) NOT NULL,  `hashtag` int(1) NOT NULL,  PRIMARY KEY (`ms`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE `morp_tags`;
CREATE TABLE `morp_tags` (  `tagID` int(11) NOT NULL AUTO_INCREMENT,  `tag_long` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `tag` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`tagID`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `morp_tags_list`;
CREATE TABLE `morp_tags_list` (  `tagListID` int(11) NOT NULL AUTO_INCREMENT,  `tagID` int(11) NOT NULL,  `targetID` int(11) NOT NULL,  `art` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`tagListID`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE `timetables`;
CREATE TABLE `timetables` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` varchar(100) NOT NULL,  `image` varchar(100) NOT NULL,  `date` varchar(10) NOT NULL,  `day` varchar(10) NOT NULL,  `start_time` varchar(10) CHARACTER SET latin1 NOT NULL,  `end_time` varchar(10) CHARACTER SET latin1 NOT NULL,  `color` int(11) NOT NULL,  `description` text NOT NULL,  `state` tinyint(4) NOT NULL DEFAULT '1',  `invite` int(11) NOT NULL,  `inviteText` varchar(255) NOT NULL,  `enddate` varchar(10) NOT NULL,  `event` int(11) NOT NULL,  `confirmed` int(1) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE `users`;
CREATE TABLE `users` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` varchar(255) NOT NULL,  `username` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `password` char(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `salt` char(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,  `role` int(11) NOT NULL,  `state` tinyint(3) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`),  UNIQUE KEY `username` (`username`),  UNIQUE KEY `email` (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
