
<?php  $output .= '<ul class="sitemap">

		<li class="parent n__1"><a href="https://www.pixeldusche.com/haindlstrnad/home/">Home</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__2"><a href="https://www.pixeldusche.com/haindlstrnad/supervision/">Supervision</a>
		 	<ul class="sub-menu2"></ul>
		</li>

		<li class="parent n__3"><a href="https://www.pixeldusche.com/haindlstrnad/coaching/">Coaching</a>
		 	<ul class="sub-menu3"></ul>
		</li>

		<li class="parent n__4"><a href="https://www.pixeldusche.com/haindlstrnad/workshops/">Workshops</a>
		 	<ul class="sub-menu4"></ul>
		</li>

		<li class="parent n__8"><a href="https://www.pixeldusche.com/haindlstrnad/aktuell/">Aktuelles</a>
		 	<ul class="sub-menu5"></ul>
		</li>

		<li class="parent n__5"><a href="https://www.pixeldusche.com/haindlstrnad/ueber-mich/">Über mich</a>
		 	<ul class="sub-menu6"></li>
</ul>
';
?>
</ul>