<?php  $output .= '<ul class="">

				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.pixeldusche.com/haindlstrnad/de/home/">Home</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.pixeldusche.com/haindlstrnad/de/supervision/">Supervision</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.pixeldusche.com/haindlstrnad/de/coaching/">Coaching</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.pixeldusche.com/haindlstrnad/de/workshops/">Workshops</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.pixeldusche.com/haindlstrnad/de/aktuell/">Aktuelles</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.pixeldusche.com/haindlstrnad/de/ueber-mich/">Über mich</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.pixeldusche.com/haindlstrnad/de/impressum/">Impressum</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.pixeldusche.com/haindlstrnad/de/datenschutz/">Datenschutz</a></strong></li>
</ul>'; ?>