
<?php  $structure = '<ul class="sitemap"><li class="closeHeader"><i class="fa fa-close"></i></li>

		<li class="parent n__1"><a data-clipboard-text="<a:1:>Link_Name</a>" class="intLink">Home</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__2"><a data-clipboard-text="<a:2:>Link_Name</a>" class="intLink">Supervision</a>
		 	<ul class="sub-menu2"></ul>
		</li>

		<li class="parent n__3"><a data-clipboard-text="<a:3:>Link_Name</a>" class="intLink">Coaching</a>
		 	<ul class="sub-menu3"></ul>
		</li>

		<li class="parent n__4"><a data-clipboard-text="<a:4:>Link_Name</a>" class="intLink">Workshops</a>
		 	<ul class="sub-menu4"></ul>
		</li>

		<li class="parent n__8"><a data-clipboard-text="<a:8:>Link_Name</a>" class="intLink">Aktuelles</a>
		 	<ul class="sub-menu5"></ul>
		</li>

		<li class="parent n__5"><a data-clipboard-text="<a:5:>Link_Name</a>" class="intLink">Über mich</a>
		 	<ul class="sub-menu6"></li>
		<li><a href="https://www.pixeldusche.com/haindlstrnad/de/impressum/" title="impressum"><strong>Impressum</strong></a></li>
			<li><a href="https://www.pixeldusche.com/haindlstrnad/de/datenschutz/" title="datenschutz"><strong>Datenschutz</strong></a></li>
	</ul>
';
?>
</ul>